### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by kamsz** [intelsdi-x/snap-plugin-collector-libvirt#14]
Metrics in README are listed as:
```
/libvirt/{domain_name}/...
```

In latest version metrics are listed as:
```
/libvirt/{host_hostname}/{domain_name}/...

**Comment by sandlbn** [comment]
@kamsz Thanks, I'm gonna push a new version of plugin Today with support for nova and I'll update README in next PR.

**Comment by sandlbn** [comment]
@kamsz I removed hostname from namespace. I will close this issue when code will be merged.

**Comment by sandlbn** [comment]
@kamsz PR was merged. Closing.
