### ISSUE TITLE
libvirt plugin reports same instance instead of multiple instances when using *

### ISSUE THREAD

**Issue by lynxbat** [intelsdi-x/snap-plugin-collector-libvirt#23]
##### ISSUE TYPE

 - Bug Report

Linking an issue posted on Snap issues here:

https://github.com/intelsdi-x/snap/issues/963

**Comment by beyossi** [comment]
as a walk-around I am reading the "snapctl metric list" where all the metrics appear correctly and creating a task json descriptor and creating that task. this works well but it means doing so for each change of vm provisioning.

**Comment by sandlbn** [comment]
@beyossi I'm working on this issue now, fix is on the way.

**Comment by sandlbn** [comment]
Fixed in #24
