### ISSUE TITLE
This plugin should restrict compiling on linux

### ISSUE THREAD

**Issue by nanliu** [intelsdi-x/snap-plugin-collector-libvirt#25]
This plugin depends on libvirt-go which is only supported on linux:
https://github.com/sandlbn/libvirt-go#os-compatibility-matrix

**Comment by sandlbn** [comment]
Not really I'm using this plugin on my MacOS box.  Also should be fully compatible with FreeBSD libvirt  Bhyve driver.

**Comment by nanliu** [comment]
My bad, I saw some compile errors and though it was limited to linux. Added Mac libvirt package install instruction in #29.
