### ISSUE TITLE
The plugin can't be loaded

### ISSUE THREAD

**Issue by cr2025x1** [intelsdi-x/snap-plugin-collector-libvirt#26]
##### ISSUE TYPE
 - Bug Report

##### SNAP VERSION
snapd version master-5137f6c

##### SNAP PLUGIN VERSION
7

##### CONFIGURATION
snapd was run with the following command:
snapd --plugin-trust 0 --log-level 1

##### OS / ENVIRONMENT
Ubuntu 14.04.2 LTS

##### SUMMARY
The plugin is can't be loaded with following message:
Error loading plugin:
A dynamic element * requires a name for namespace /libvirt/*/cpu/cputime.

##### STEPS TO REPRODUCE
Just the following command:
snapctl plugin load plugins/snap-plugin-collector-libvirt

##### EXPECTED RESULTS
Of course, the plugin should be loaded.

##### ACTUAL RESULTS
This is the related logs from snapd:
INFO[2016-08-03T16:54:57+09:00] API request                                   _module=_mgmt-rest index=1 method=POST url=/v1/plugins
DEBU[2016-08-03T16:54:59+09:00] wrote 9428088 to /tmp/766998591/snap-plugin-collector-libvirt
INFO[2016-08-03T16:55:00+09:00] Loading plugin: /tmp/766998591/snap-plugin-collector-libvirt  _module=_mgmt-rest
INFO[2016-08-03T16:55:00+09:00] plugin load called                            _block=load _module=control
INFO[2016-08-03T16:55:00+09:00] plugin load called                            _block=load-plugin _module=control-plugin-mgr path=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method Decode reply type not a pointer: interface {}  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method Decrypt has wrong number of ins: 2  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method DecryptKey has wrong number of ins: 2  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method Encode has wrong number of ins: 2  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method Encrypt has wrong number of ins: 2  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method EncryptKey has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method KillChan has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method ListenAddress has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method ListenPort has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method Logger has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method ResetHeartbeat has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method SetEncrypter has wrong number of ins: 2  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method SetListenAddress has wrong number of ins: 2  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] 2016/08/03 16:55:00 method Token has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=snap-plugin-collector-libvirt
DEBU[2016-08-03T16:55:00+09:00] Getting plugin config                         _block_=getPluginConfigDataNode _module=config config-cache-key=0:libvirt:7 config-cache-value=&{mutex:0xc82034bd38 table:map[]}
ERRO[2016-08-03T16:55:00+09:00] error adding loaded metric type               _block=add-loaded-metric-type _file=metrics.go, _module=control error=Metric namespace /libvirt/*/cpu/cputime is invalid
ERRO[2016-08-03T16:55:00+09:00] error adding loaded metric type               _block=load-plugin _module=control-plugin-mgr error=A dynamic element * requires a name for namespace /libvirt/*/cpu/cputime. metric-namespace=/libvirt/*/cpu/cputime metric-version=7 plugin-name=libvirt plugin-path=766998591 plugin-type=collector plugin-version=7
ERRO[2016-08-03T16:55:00+09:00] A dynamic element * requires a name for namespace /libvirt/*/cpu/cputime.  _module=_mgmt-rest
DEBU[2016-08-03T16:55:00+09:00] Removing file (/tmp/766998591/snap-plugin-collector-libvirt)  _module=_mgmt-rest
INFO[2016-08-03T16:55:00+09:00] API response                                  _module=_mgmt-rest index=1 method=POST status=Internal Server Error status-code=500 url=/v1/plugins

The following is the response error message from snapctl:
Error loading plugin:
A dynamic element * requires a name for namespace /libvirt/*/cpu/cputime.

@intelsdi-x/plugin-maintainers

**Comment by cr2025x1** [comment]
I think the problem is occurring due to the change made by the recent commit on intelsdi-x/snap.
https://github.com/intelsdi-x/snap/commit/47b789cd97c83ca5b58d440acb2892e346228ebf

Lines from 355:356 catches the namespace of plugin.MetricType object generated by the lines 236:240 from libvirt.go(https://github.com/intelsdi-x/snap-plugin-collector-libvirt/blob/master/libvirt/libvirt.go) and report a error as the namespace contains "*" in it.

Removing these lines solved the issue and the plugin works well.

**Comment by katarzyna-z** [comment]
@sandlbn  Could you confirm that this is resolved by pull request #30 and close this issue?

**Comment by sandlbn** [comment]
@katarzyna-z yes that was resolved.
