### ISSUE TITLE
Refactor this code

### ISSUE THREAD

**Issue by lmroz** [intelsdi-x/snap-plugin-collector-libvirt#28]
I don't feel like opening three issues for this code, but this really needs to be refactored:
- There is copy & paste all over the code (it's actually most of it within and across all files related to collection of data).
- There is no separation between snap interaction & metrics collection. In such simple case we may live without separate package but at leas within main one functions should deal only with collection or only with namespaces or only with snap api.
- Functions that can return error, should use this opportunity instead of panic (unless it's really justified, but I don't see the case in this plugin). So please remove `handleErr`.

@intelsdi-x/plugin-maintainers

**Comment by sandlbn** [comment]
For sure plugin needs to be updated, this was one of the earliest plugins available on snap and never (except small changes) updated from the start. You can assign me to this issue.
