### ISSUE TITLE
DB schema not as expected when used in conjunction with InfluxDB-Publisher

### ISSUE THREAD

**Issue by dgarth** [intelsdi-x/snap-plugin-collector-libvirt#39]
When using, for example, the [CPU-collector](https://github.com/intelsdi-x/snap-plugin-collector-cpu) and the [InfluxDB-publisher](https://github.com/intelsdi-x/snap-plugin-publisher-influxdb) you get a measurement-table called "intel/procfs/cpu/active_percentage" in the database where additional information, i.e. the number of the CPU core and the sources hostname, are saved as tags for the measurement. You can then filter in the WHERE clause of your query using these tags. The behaviour is similar for the [network-](https://github.com/intelsdi-x/snap-plugin-collector-interface) and [disk-collector-plugins](https://github.com/intelsdi-x/snap-plugin-collector-disk) when it comes to names of disks or network interfaces.
In contrast to this, when you use the libvirt-collector-plugin all these identifiers (CPU core, network interface, disk name, source domain name) are saved in the name of the measurement itself (e.g. "libvirt/instance-00000001/cpu/vcpu/0/cputime" instead of "libvirt/cpu/vcpu/cputime"). The problem is, to get the name of e.g. all network interfaces on a certain instance you would need to search through all the measurements names and extract them (e.g. via regex) in your application code instead of just calling "SHOW TAG KEYS" or "SHOW TAG VALUES" in InfluxDB. Also, in an environment with a big throughput of VMs the database will be cluttered with big amounts of tables.

**Comment by sandlbn** [comment]
This is well know problem with some plugins #36 is addressing  this bug.

**Comment by sandlbn** [comment]
Fixed in #36
