### ISSUE TITLE
Libvirt can report only statistics from first network interface

### ISSUE THREAD

**Issue by sandlbn** [intelsdi-x/snap-plugin-collector-libvirt#43]
**Environment**:
Any OS with multiple nics

We are using kvm, and we have configured the missing metrics (memory/available etc) to be collected.
We have updated the plugin version 10,
we have still not managed to get via snap plugin the metrics, we are working on it.
yet we are encountering now a different problem with the new plugin version -
in the former version we have used the option "snapctl metric list" to get all the possible VM's and their interfaces, and it worked fine.
Now, with the new plugin version, we noticed that only a single interface per VM is fetched by this option,
that is, if we have 3 VM's and each has 3 interfaces configured,
now it will fetch only a single interface per VM.
Can this be fixed?

**Steps to reproduce it** (as minimally and precisely as possible):

1. 
2. 
3. 

**Anything else do we need to know** (e.g. issue happens only occasionally):

**Comment by diziup** [comment]
Hi,
We have tried the new plugin and the metrics returned are still 0.
In contrast, we have configured our VM's so that virsh now fetches them with values:
virsh dommemstat l3fwd-1 
actual 6291456
swap_in 0
swap_out 0
major_fault 635
minor_fault 136290
unused 3827484
available 6110524
rss 2866048

Can you please elaborate on the exact way that libvirt plugin retrieves these metrics?
perhaps we can reproduce them in our machine.

**Comment by sandlbn** [comment]
@diziup as I said before I only fixed this issue, https://github.com/intelsdi-x/snap-plugin-collector-libvirt/issues/43, this one remain open, it involves debugging libvirt library. I will update status of this issue tomorrow.

**Comment by sandlbn** [comment]
@diziup Can you paste me your host configuration, are you using RedHat/Centos or Ubuntu ? Please also provide version of your OS.

**Comment by diziup** [comment]
[memOut.txt](https://github.com/intelsd
[memOut.txt](https://github.com/intelsdi-x/snap-plugin-collector-libvirt/files/629366/memOut.txt)
i-x/snap-plugin-collector-libvirt/files/629365/memOut.txt)


Host:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

Linux david 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux


meminfo
MemTotal:       32826488 kB
MemFree:         4245432 kB
MemAvailable:   16070628 kB
Buffers:          223048 kB
Cached:         11553680 kB
SwapCached:        70376 kB
Active:         23311404 kB
Inactive:        4055460 kB
Active(anon):   15544460 kB
Inactive(anon):    70444 kB
Active(file):    7766944 kB
Inactive(file):  3985016 kB
Unevictable:        3660 kB
Mlocked:            3660 kB
SwapTotal:      33457148 kB
SwapFree:       33356880 kB
Dirty:               224 kB
Writeback:             0 kB
AnonPages:      15534096 kB
Mapped:           126304 kB
Shmem:             22320 kB
Slab:             750680 kB
SReclaimable:     480120 kB
SUnreclaim:       270560 kB
KernelStack:       11472 kB
PageTables:        57432 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    49870392 kB
Committed_AS:   35036796 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:  12926976 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      373484 kB
DirectMap2M:    20502528 kB
DirectMap1G:    14680064 kB


cpu:
there are 20 virtual cpu's with the following configuration:
processor       : 19
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
stepping        : 1
microcode       : 0xb000014
cpu MHz         : 1200.093
cache size      : 25600 KB
physical id     : 0
siblings        : 20
core id         : 12
cpu cores       : 10
apicid          : 25
initial apicid  : 25
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
bugs            :
bogomips        : 4800.07
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:


The host model: Dell r630

**Comment by diziup** [comment]
the test output and the host configuration are attached above

**Comment by sandlbn** [comment]
@diziup Thanks that's great. But this info comes from /proc/meminfo . I'm more interested in output from attached binary . https://drive.google.com/file/d/0B0iNIa564eX0RmluWmtXNk1SMVk/view?usp=sharing . Can you run this on your system ?

**Comment by diziup** [comment]
5
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
6 6291456
0 0
1 0
2 764
3 864388
4 3446944
5 6110792
7 3297852
8
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
6 6291456
0 0
1 0
2 764
3 864388
4 3446944
5 6110792
7 3297852
10
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
6 6291456
0 0
1 0
2 764
3 864388
4 3446944
5 6110792
7 3297852
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
6 6291456
0 0
1 0
2 765
3 847393
4 3482564
5 6110792
7 3249796
8
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
6 6291456
0 0
1 0
2 765
3 847393
4 3482564
5 6110792
7 3249796
10
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
6 6291456
0 0
1 0
2 765
3 847393
4 3482564
5 6110792
7 3249796
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
6 6291456
0 0
1 0
2 774
3 736323
4 3455496
5 6110524
7 3311856
8
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
6 6291456
0 0
1 0
2 774
3 736323
4 3455496
5 6110524
7 3311856
10
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
6 6291456
0 0
1 0
2 774
3 736323
4 3455496
5 6110524
7 3311856

**Comment by diziup** [comment]
This is the output (I attached it in the previous correspondence)

**Comment by diziup** [comment]
any update?

**Comment by diziup** [comment]
??

**Comment by sandlbn** [comment]
As I wrote before I'm on the vacation now and memory bug will be fixed
after Christmas. This bug I'm referring to the Memory usage issue is not
high priority bug. based on my findings, it only affects some libvirt
versions and builds. Also network bug it's fixed in #43 PR.

**Comment by IzabellaRaulin** [comment]
Hello @diziup, I reviewed pull request https://github.com/intelsdi-x/snap-plugin-collector-libvirt/pull/44 which resolves an issue related to retrieving network statistics. I would like to merge this one to allow collecting metrics from all interfaces. I will open a new issue to address memory usage issue that occurs on your setup.

**Comment by diziup** [comment]
Ok,
thanks,
So this is on hold until after Christmas?

**Comment by diziup** [comment]
Hi,
we have tried again libvirt plugin version 10 and we are still encountering an issue as I have noted in the previous correspondence:
using "snapctl metric list" to get all the possible VM's and their interfaces results in  only a single interface per VM that is fetched by this option,
that is, if we have 3 VM's and each has 3 interfaces configured,
now it will fetch only a single interface per VM.
This is crucial for us,
help will be appreciated.
Thanks!
