### ISSUE TITLE
Domain names are not refreshed since the plugin is loaded

### ISSUE THREAD

**Issue by EvgenyAGRO** [intelsdi-x/snap-plugin-collector-libvirt#48]
**Snap daemon version**: 0.18.0

**Environment**:
- **Hardware configuration**: Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, 32G RAM
- **OS**: Ubuntu 16.04.1 LTS
- **Kernel**: Linux  4.4.0-57-generic x86_64 GNU/Linux
- **Relevant tools**: Libvirt

**What happened**:
I've loaded the libvirt plugin a while ago, since then some of my domains went down, libvirt plugin failed to recognize that some of the domain have changed and when I've started another task which collect various metrics from available domains it started to fail, I've looked in snapd.log and found that the plugin was trying to collect metrics from an already non existent domains when these domains weren't explicitly inserted as part of the metrics(general metrics were used, like /libvirt/*/). 

**What you expected to happen**:
I think that it makes sense to refresh once in a while the available domains and update the available metrics if necessary. I'd expect the "/libvirt/*/" metric to expand to available domains only.

**Steps to reproduce it**:

1. Load libvirt plugin
2. Remove a certain domain (e.g via virsh).
3. Run libvirt task (on available domains for example by collecting all possible metrics with /libvirt/*/)

**Comment by sandlbn** [comment]
@EvgenyAGRO can you check, which version of plugin are u using ? Is it latest version ? New version of plugin have "autodiscovery" build in.

**Comment by EvgenyAGRO** [comment]
@sandlbn Oh, didn't notice, indeed I'm using version 8.

**Comment by sandlbn** [comment]
@EvgenyAGRO you can grab latest version from our CI http://snap.ci.snap-telemetry.io/plugins/snap-plugin-collector-libvirt/latest_build/linux/x86_64/snap-plugin-collector-libvirt

**Comment by nanliu** [comment]
@EvgenyAGRO, did you get a chance to try [a newer release](https://github.com/intelsdi-x/snap-plugin-collector-libvirt/releases)?

**Comment by sandlbn** [comment]
I will close this, no response by last 16 days and patch for this issue was released.
