### ISSUE TITLE
Libvirt 

### ISSUE THREAD

**Issue by diziup** [intelsdi-x/snap-plugin-collector-libvirt#51]
Snap daemon version:1.0.0
Hardware configuration: Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, 32G RAM
OS: Ubuntu 16.04.1 LTS
Kernel: Linux 4.4.0-57-generic x86_64 GNU/Linux
Relevant tools: Libvirt
We have 2 vm's configured in the host, where they are vyatta 5600 vRouter,
where the vm's inter-communication is by Linux bridge taps.

**What happened**:
We have updated to libvirt v12, 
and are encountering several problems:
1. Metrics from all possible vm's in host are measured, with no regards to what is written in the task json file used to create the task.
For instance, the json manifest file contains metrics that are related only to a single vm, yet in the metrics measured by the task we see metrics from other vm's as well.
In the command "snaptel metric list" we indeed see that the format has changed,
and there is no-backward compatibility (to as was in v8).
This is a huge drawback to us, as the entire task creation mechanism we developed was written on a per -VM basis (for optimization matters).

2. The same metrics are measured twice (seen in task watch).

**What you expected to happen**:
1. Only the metrics given in the manifest file should be measured
2. These metrics should be measured once (and appear so in the task watch)

**Steps to reproduce it** (as minimally and precisely as possible):

1. Create a host with 2 vm's (of some type )
2. Create a task that applies only to a single vm metrics
3. 

**Anything else do we need to know** (e.g. issue happe
[vm1_forwarding_libvirt.txt](https://github.com/intelsdi-x/snap-plugin-collector-libvirt/files/801990/vm1_forwarding_libvirt.txt)

*The manifest file is attached.

sudo virsh list:
 Id    Name                           State
----------------------------------------------------
 5     l3fwd-1                        running
 6     l3fwd-2                        running

**Comment by PatrykMatyjasek** [comment]
@sandlbn Could you take a look at this issue?

**Comment by sandlbn** [comment]
@diziup Hi, we never have (lab) any requirements for the granularity of  libvirt probes but it's nice to hear that you need it.  I'll take a look now .
