### ISSUE TITLE
the metrics collected by libvirt plugin, cputime is not equal to sum(vcputime)

### ISSUE THREAD

**Issue by sunkevin6** [intelsdi-x/snap-plugin-collector-libvirt#62]
**Snap daemon version** (use `snapteld -v`):
snapteld version 1.2.0

**Environment**:
- **Cloud provider or hardware configuration**:

- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- **Kernel** (e.g. `uname -a`):
Linux rk012-s13 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- **Relevant tools** (e.g. plugins used with Snap):
root@rk012-s13:/tmp/skw# /opt/snapd/snaptel plugin list
NAME 		 VERSION 	 TYPE 		 SIGNED 	 STATUS 	 LOADED TIME
libvirt 	 14 		 collector 	 false 		 loaded 	 Tue, 31 Oct 2017 19:13:05 UTC
kafka 		 1 		 publisher 	 false 		 loaded 	 Tue, 31 Oct 2017 19:13:07 UTC
cpu 		 6 		 collector 	 false 		 loaded 	 Tue, 31 Oct 2017 19:12:58 UTC
meminfo 	 3 		 collector 	 false 		 loaded 	 Tue, 31 Oct 2017 19:13:00 UTC
load 		 3 		 collector 	 false 		 loaded 	 Tue, 31 Oct 2017 19:13:01 UTC
df 		 6 		 collector 	 false 		 loaded 	 Tue, 31 Oct 2017 19:13:02 UTC
iface 		 4 		 collector 	 false 		 loaded 	 Tue, 31 Oct 2017 19:13:03 UTC
pstate 		 1 		 collector 	 false 		 loaded 	 Tue, 31 Oct 2017 19:13:04 UTC

- **Others** (e.g. deploying with Ansible):

**What happened**:
We are using snaptel(d) and libvirt plugin to collect metrics of VMs.
And we try to extend the official snap libvirt plugin to calculate cpu usage percentage.
The formula is
cpu_percentage = 100 * (curCpuTime - preCpuTime) / (curSysCpuTime - preSysCpuTime) / vm_cores

var tv syscall.Timeval
syscall.Gettimeofday(&tv)
sysCpuTime = (uint64(tv.Sec)*1e9 + uint64(tv.Usec)*1e3)

cpuTime, err := wrapper.GetCPUStatistics(id)

And we also calculate
vcpu_percenagte = 100 * (curVcpuTime - preVcpuTime) / (curSysCpuTime - preSysCpuTime)

vcpuTime, err := wrapper.GetVCPUStatistics(id)

But faced an issue, sometimes, the cpu_percentage is over than 100%, but we already normalized it by vm_cores. And this has not happened on vcpu_percentage.
And finally, we check the value of cpuTime with sum(vcpuTime), we found the values are very different.

time="2017-10-27T13:54:26Z" level=debug msg="time=\"2017-10-27T13:54:26Z\" level=info msg=\"Compare domainName: 24b60ef2-4763-4ca6-ad68-0865260f735e,  CpuTime: 301520000000 with sumVcpuTime: 246200000000, vm_cores: 2\"" _module=plugin-exec io=stderr plugin=libvirt

Now, we confuse which value are accurate? And how to collect cpuTime? Becasue our analytics team cannot accept the cpu_percentage is over than 100% after we normalized by vm_cores.

**What you expected to happen**:
1. We think the cputime maybe equal to sum(vcputime)
2. When we calculate cputime_percentage based on cputime, it should not over than 100% after we normalized it by vm_cores.

**Steps to reproduce it** (as minimally and precisely as possible):

1.  on your current libvirt plugin, collect cputime and sum(vcputime)
2. on your vm, run "dd if=/dev/zero of=/dev/null &". if you have two cores, run it twice.
3. 

**Anything else do we need to know** (e.g. issue happens only occasionally):

**Comment by sandlbn** [comment]
Actually we already implemented utilization in out dev version of plugin. We are calculating this value as 
```
func virtualUtilization(cpuTimeNow int64, cpuTimePrev int64, deltaTime int64, numberOfCores int64) int64 {
	var utilization int64
	return 100 * (cpuTimeNow - cpuTimePrev) / (deltaTime * numberOfCores * 1000000000)
}
```
Never seen any spike that is going higher then 100% I will try to upload this code over this week for testing. 

If you see any spikes above 100% , it can mean that your deltatime was not measured precisely.  
Here is screenshot from our implementation. (It shows vm utilize by the stress-ng package)
![screen shot 2017-10-31 at 21 30 59](https://user-images.githubusercontent.com/2578718/32250040-e67d2452-be82-11e7-9226-5072817b1a35.png)

**Comment by Yajuan-Shi** [comment]
From code side, snap libvirt collector use cpuTime as virDomainInfo::cpuTime  
                             And each vCPU time use virVcpuInfo::cpuTime 
 Find a similar topic: https://www.redhat.com/archives/libvirt-users/2010-August/msg00024.html
